#!/bin/bash
# Quick guide to get SSH Key ID from Hetzner

echo "🔍 How to Get Your SSH Key ID from Hetzner"
echo "=========================================="
echo ""
echo "You've added your SSH key to Hetzner. Now you need the ID."
echo ""
echo "📋 Method 1: Via Hetzner Web Console (Easiest)"
echo "----------------------------------------------"
echo "1. Go to: https://console.hetzner.cloud/"
echo "2. Select your project"
echo "3. Click: Security → SSH Keys"
echo "4. You'll see a list of your SSH keys"
echo "5. Look for the 'ID' column - it's a number like: 12345678"
echo ""
echo "   Example:"
echo "   ┌─────────────────────────────────────────┐"
echo "   │ ID: 12345678  Name: WireGuard VPN Key   │"
echo "   │ Fingerprint: aa:bb:cc:dd:ee:ff...       │"
echo "   └─────────────────────────────────────────┘"
echo "          ↑"
echo "     This is your SSH Key ID!"
echo ""
echo "📋 Method 2: Via hcloud CLI (Advanced)"
echo "--------------------------------------"
echo ""

# Check if hcloud is installed
if command -v hcloud &>/dev/null; then
	echo "✅ hcloud CLI is installed!"
	echo ""
	echo "Fetching your SSH keys..."
	echo ""
	hcloud ssh-key list
	echo ""
	echo "👆 The first column shows your SSH Key IDs"
else
	echo "⚠️  hcloud CLI is not installed."
	echo ""
	echo "To install:"
	echo "  curl -L https://github.com/hetznercloud/cli/releases/latest/download/hcloud-linux-amd64.tar.gz | tar xz"
	echo "  sudo mv hcloud /usr/local/bin/"
	echo ""
	echo "Then configure:"
	echo "  hcloud context create my-project"
	echo "  # Paste your API token when prompted"
	echo ""
	echo "And list keys:"
	echo "  hcloud ssh-key list"
fi

echo ""
echo "📝 Next Steps"
echo "-------------"
echo "After getting your SSH Key ID (e.g., 12345678):"
echo ""
echo "1️⃣  Update terraform/terraform.tfvars:"
echo "    ssh_key_ids = [12345678]"
echo ""
echo "2️⃣  Or if using multiple keys:"
echo "    ssh_key_ids = [12345678, 87654321]"
echo ""
echo "3️⃣  For GitHub Actions, add secret 'SSH_KEY_IDS':"
echo "    [12345678]"
echo ""
echo "Ready to deploy? 🚀"
echo ""
